import '../styles/globals.css'
import Head from 'next/head';
import { RecoilRoot } from 'recoil';
import type { AppProps } from 'next/app'

export default function App({ Component, pageProps }: AppProps) {
  return ( 
    <div className='w-full h-screen scrollbar-thin scrollbar-thumb-white/60 scrollbar-track-transparent snap-y snap-mandatory overflow-y-scroll scroll-smooth'>
      <Head>
        <title>Emigrek - portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RecoilRoot>
          <Component {...pageProps} />
        </RecoilRoot>
      </main>
    </div>
  );
}
